[project]
name = "tenseur"
version = "1.0.0"
authors = [
  { name="Marc Nawman", email="mailnawman@gmail.com" },
]
description = "Tensor and mathematical library"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Linux",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/istmarc/tenseurpy"
Issues = "https://github.com/"

